
plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = 21
    targetCompatibility = 21
}

dependencies {
    testImplementation "org.junit.jupiter:junit-jupiter:${junitVersion}"
    implementation "com.squareup.retrofit2:retrofit:${retrofitVersion}"
    implementation "com.squareup.retrofit2:converter-jackson:${retrofitJacksonVersion}"
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    implementation "org.slf4j:slf4j-api:${slf4jVersion}"
    runtimeOnly "ch.qos.logback:logback-classic:${logbackVersion}"
    implementation "com.squareup.okhttp3:logging-interceptor:${okhttpLoggingVersion}"
    testImplementation "org.assertj:assertj-core:${assertjVersion}"
}

test {
    testLogging {
        events("passed", "skipped", "failed")
        showStandardStreams = true
    }
    useJUnitPlatform()
}
