apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: testing-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts:
            - name: secrets-store-inline
              mountPath: /mnt/secrets-store
              readOnly: true
          env: 
            - name: ARGS
              value: "{{ .Values.env.ARGS }}"
{{- $kv := .Values.keyVault }}
{{- range $k, $v := $kv }}
{{- if and (kindIs "map" $v) (hasKey $v "jmesPath") }}
{{- range $i, $item := $v.jmesPath }}
            - name: {{ $item.path | replace "-" "_" | upper }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.kubeSecretReferenceName }}
                  key: {{ $item.path }}
{{- end }}
{{- end }}
{{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecret }}
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ $.Release.Name }}
      restartPolicy: Never
