region: eu-north-1
namespace: default
serviceAccountName: default
kubeSecretReferenceName: set-ai-secret

env:
  ARGS: ""

image:
  repository: registry.git.epam.com/epmc-tedu/ai_playground/pet-store-java-gradle-api-tests
  tag: latest
  pullPolicy: IfNotPresent
  imagePullSecret: docker-secret

keyVault:
  enabled: true
  
  api-secrets:
    objectType: secretsmanager
    jmesPath:
      - path: "bff-api-key"
